-- ============================================================================
--  IBKR Data — SQLite schema & seed data
--  Usage:  sqlite3 market_data.db < init.sql
-- ============================================================================

-- ---------------------------------------------------------------------------
--  1. Metadata tables
-- ---------------------------------------------------------------------------

-- Tracks which days have been scraped per ticker/source/timeframe
CREATE TABLE IF NOT EXISTS cache (
    ticker    TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    day       TEXT NOT NULL,
    source    TEXT NOT NULL DEFAULT 'ibkr',
    PRIMARY KEY (ticker, timeframe, day, source)
);

-- Reference universe of tradeable tickers
CREATE TABLE IF NOT EXISTS tickers (
    symbol TEXT PRIMARY KEY,
    name   TEXT,
    sector TEXT
);

-- ---------------------------------------------------------------------------
--  2. Seed the ticker universe  (all tickers from DB)
-- ---------------------------------------------------------------------------
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('A', 'Agilent Technologies Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AAPL', 'Apple Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ABBV', 'AbbVie Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ABNB', 'Airbnb', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ABT', 'Abbott Laboratories', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ACGL', 'Arch Capital Group', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ACN', 'Accenture', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ADBE', 'Adobe Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ADI', 'Analog Devices', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ADM', 'Archer Daniels Midland', 'Consumer Staples');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ADP', 'Automatic Data Processing Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ADSK', 'Autodesk', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AEE', 'Ameren', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AEP', 'American Electric Power', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AES', 'AES Corporation', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AFL', 'Aflac Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AIG', 'American International Group Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AIZ', 'Assurant', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AJG', 'Arthur J. Gallagher & Co.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AKAM', 'Akamai Technologies Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ALB', 'Albemarle Corp.', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ALGN', 'Align Technology', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ALL', 'Allstate Corp.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ALLE', 'Allegion', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AMAT', 'Applied Materials Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AMCR', 'Amcor', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AMD', 'Advanced Micro Devices Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AME', 'Ametek Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AMGN', 'Amgen Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AMP', 'Ameriprise Financial', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AMT', 'American Tower Corp.', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AMZN', 'Amazon.com Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ANET', 'Arista Networks', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ANSS', 'Ansys Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AON', 'Aon PLC', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AOS', 'A. O. Smith', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('APA', 'APA Corporation', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('APD', 'Air Products & Chemicals Inc.', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('APH', 'Amphenol', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('APO', 'Apollo Global Management', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('APP', 'AppLovin', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('APTV', 'Aptiv', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ARE', 'Alexandria Real Estate Equities Inc.', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ARES', 'Ares Management', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ARM', 'ARM Holdings PLC (ADR)', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ASML', 'ASML Holding NV (ADR)', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ATO', 'Atmos Energy', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AVB', 'AvalonBay Communities Inc.', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AVGO', 'Broadcom Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AVY', 'Avery Dennison', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AWK', 'American Water Works', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AXON', 'Axon Enterprise', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AXP', 'American Express Co.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AZN', 'AstraZeneca PLC (ADR)', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('AZO', 'AutoZone Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BA', 'The Boeing Co.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BAC', 'Bank of America Corp.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BALL', 'Ball Corporation', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BAX', 'Baxter International', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BBY', 'Best Buy Co. Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BDX', 'Becton Dickinson & Co.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BEN', 'Franklin Resources', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BF.B', 'Brown–Forman', 'Consumer Staples');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BG', 'Bunge Global', 'Consumer Staples');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BIIB', 'Biogen Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BKNG', 'Booking Holdings', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BKR', 'Baker Hughes Co.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BLDR', 'Builders FirstSource', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BLK', 'BlackRock Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BMY', 'Bristol Myers Squibb', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BNY', 'BNY Mellon', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BR', 'Broadridge Financial Solutions', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BRK.B', 'Berkshire Hathaway Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BRO', 'Brown & Brown', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BSX', 'Boston Scientific Corp.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BX', 'Blackstone Inc.', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('BXP', 'BXP, Inc.', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('C', 'Citigroup Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CAG', 'Conagra Brands Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CAH', 'Cardinal Health', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CARR', 'Carrier Global Corp.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CASY', 'Casey''s', 'Consumer Staples');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CAT', 'Caterpillar Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CB', 'Chubb Ltd.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CBOE', 'Cboe Global Markets', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CBRE', 'CBRE Group', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CCI', 'Crown Castle Inc.', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CCL', 'Carnival Corporation', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CDNS', 'Cadence Design Systems Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CDW', 'CDW Corporation', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CEG', 'Constellation Energy', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CF', 'CF Industries Holdings Inc.', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CFG', 'Citizens Financial Group', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CHD', 'Church & Dwight', 'Consumer Staples');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CHRW', 'C.H. Robinson', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CHTR', 'Charter Communications Inc.', 'Communication');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CI', 'Cigna Group', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CIEN', 'Ciena', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CINF', 'Cincinnati Financial', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CL', 'Colgate-Palmolive Co.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CLX', 'Clorox', 'Consumer Staples');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CMCSA', 'Comcast Corp.', 'Communication');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CME', 'CME Group Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CMG', 'Chipotle Mexican Grill', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CMI', 'Cummins Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CMS', 'CMS Energy', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CNC', 'Centene Corp.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CNP', 'CenterPoint Energy', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('COF', 'Capital One Financial Corp.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('COHR', 'Coherent Corp.', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('COIN', 'Coinbase', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('COO', 'Cooper Companies (The)', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('COP', 'ConocoPhillips', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('COR', 'Cencora', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('COST', 'Costco Wholesale Corp.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CPAY', 'Corpay', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CPB', 'Campbell''s Co.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CPRT', 'Copart', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CPT', 'Camden Property Trust', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CRH', 'CRH plc', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CRL', 'Charles River Laboratories', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CRM', 'Salesforce Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CRWD', 'CrowdStrike Holdings Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CSCO', 'Cisco Systems Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CSGP', 'CoStar Group', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CSX', 'CSX Corp.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CTAS', 'Cintas', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CTSH', 'Cognizant', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CTVA', 'Corteva Inc.', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CVNA', 'Carvana', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CVS', 'CVS Health Corp.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('CVX', 'Chevron Corp.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('D', 'Dominion Energy', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DAL', 'Delta Air Lines Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DASH', 'DoorDash', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DD', 'DuPont de Nemours Inc.', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DDOG', 'Datadog Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DE', 'Deere & Co.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DECK', 'Deckers Outdoor Corp.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DELL', 'Dell Technologies Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DG', 'Dollar General Corp.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DGX', 'Quest Diagnostics Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DHI', 'D. R. Horton', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DHR', 'Danaher Corp.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DIS', 'Walt Disney Co.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DLR', 'Digital Realty Trust Inc.', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DLTR', 'Dollar Tree Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DOC', 'Healthpeak Properties', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DOV', 'Dover Corp.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DOW', 'Dow Inc.', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DPZ', 'Domino''s', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DRI', 'Darden Restaurants', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DTE', 'DTE Energy', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DUK', 'Duke Energy', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DVA', 'DaVita', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DVN', 'Devon Energy Corp.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('DXCM', 'Dexcom Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EA', 'Electronic Arts Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EBAY', 'eBay Inc.', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ECL', 'Ecolab Inc.', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ED', 'Consolidated Edison', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EEM', 'iShares MSCI Emerging Markets ETF', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EFX', 'Equifax', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EG', 'Everest Group', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EIX', 'Edison International', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EL', 'Estee Lauder Companies Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ELV', 'Elevance Health Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EME', 'Emcor', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EMN', 'Eastman Chemical Co.', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EMR', 'Emerson Electric Co.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ENPH', 'Enphase Energy Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ENTG', 'Entegris Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EOG', 'EOG Resources Inc.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EQIX', 'Equinix Inc.', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EQR', 'Equity Residential', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EQT', 'EQT Corporation', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ERIE', 'Erie Indemnity', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ES', 'Eversource Energy', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ESS', 'Essex Property Trust', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ETN', 'Eaton Corp. PLC', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ETR', 'Entergy', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EVRG', 'Evergy', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EW', 'Edwards Lifesciences Corp.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EXC', 'Exelon', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EXE', 'Expand Energy', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EXPD', 'Expeditors International', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EXPE', 'Expedia Group', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('EXR', 'Extra Space Storage', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('F', 'Ford Motor Company', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FANG', 'Diamondback Energy Inc.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FAST', 'Fastenal', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FCX', 'Freeport-McMoRan Inc.', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FDS', 'FactSet', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FDX', 'FedEx Corp.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FDXF', 'FedEx Freight', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FE', 'FirstEnergy', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FFIV', 'F5 Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FICO', 'Fair Isaac', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FIS', 'Fidelity National Information Services', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FISV', 'Fiserv', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FITB', 'Fifth Third Bancorp', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FIX', 'Comfort Systems USA', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FMC', 'FMC Corp.', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FOX', 'Fox Corporation (Class B)', 'Communication Services');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FOXA', 'Fox Corp.', 'Communication');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FRT', 'Federal Realty Investment Trust', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FSLR', 'First Solar Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FTNT', 'Fortinet Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('FTV', 'Fortive', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GD', 'General Dynamics Corp.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GDDY', 'GoDaddy', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GE', 'General Electric Co.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GEHC', 'GE HealthCare Technologies Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GEN', 'Gen Digital', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GEV', 'GE Vernova', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GILD', 'Gilead Sciences Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GIS', 'General Mills Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GL', 'Globe Life', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GLW', 'Corning Inc.', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GM', 'General Motors', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GNRC', 'Generac', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GOOG', 'Alphabet Inc. (Class C)', 'Communication Services');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GOOGL', 'Alphabet Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GPC', 'Genuine Parts Company', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GPN', 'Global Payments', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GRMN', 'Garmin', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GS', 'Goldman Sachs Group Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('GWW', 'W.W. Grainger Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HAL', 'Halliburton Co.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HAS', 'Hasbro', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HBAN', 'Huntington Bancshares Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HCA', 'HCA Healthcare', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HD', 'The Home Depot Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HES', 'Hess Corp.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HIG', 'Hartford (The)', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HII', 'Huntington Ingalls Industries', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HLT', 'Hilton Worldwide', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HOLX', 'Hologic Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HON', 'Honeywell International Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HOOD', 'Robinhood Markets', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HPE', 'Hewlett Packard Enterprise Co.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HPQ', 'HP Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HRL', 'Hormel Foods Corp.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HSIC', 'Henry Schein', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HST', 'Host Hotels & Resorts', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HSY', 'Hershey Company (The)', 'Consumer Staples');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HUBB', 'Hubbell Incorporated', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HUBS', 'HubSpot Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HUM', 'Humana Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('HWM', 'Howmet Aerospace Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('IBKR', 'Interactive Brokers', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('IBM', 'International Business Machines', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ICE', 'Intercontinental Exchange Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('IDXX', 'IDEXX Laboratories Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('IEX', 'IDEX Corporation', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('IFF', 'International Flavors & Fragrances Inc.', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ILMN', 'Illumina Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('INCY', 'Incyte', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('INTC', 'Intel Corp.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('INTU', 'Intuit Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('INVH', 'Invitation Homes', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('IP', 'International Paper', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('IPG', 'Interpublic Group of Cos. Inc.', 'Communication');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('IQV', 'IQVIA', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('IR', 'Ingersoll Rand Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('IRM', 'Iron Mountain', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ISRG', 'Intuitive Surgical Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('IT', 'Gartner', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ITW', 'Illinois Tool Works Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('IVZ', 'Invesco', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('J', 'Jacobs Solutions', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('JBHT', 'JB Hunt Transport Services Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('JBL', 'Jabil', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('JCI', 'Johnson Controls', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('JKHY', 'Jack Henry & Associates', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('JNJ', 'Johnson & Johnson', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('JPM', 'JPMorgan Chase & Co.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('K', 'Kellanova', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('KDP', 'Keurig Dr Pepper', 'Consumer Staples');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('KEY', 'KeyCorp', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('KEYS', 'Keysight Technologies Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('KHC', 'Kraft Heinz Co.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('KIM', 'Kimco Realty', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('KKR', 'KKR & Co.', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('KLAC', 'KLA Corp.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('KMB', 'Kimberly-Clark', 'Consumer Staples');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('KMI', 'Kinder Morgan Inc.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('KO', 'Coca-Cola Co.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('KR', 'Kroger Co.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('KVUE', 'Kenvue', 'Consumer Staples');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('L', 'Loews Corporation', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LDOS', 'Leidos', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LEN', 'Lennar', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LH', 'Labcorp Holdings Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LHX', 'L3Harris Technologies Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LII', 'Lennox International', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LIN', 'Linde PLC', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LITE', 'Lumentum', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LLY', 'Eli Lilly & Co.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LMT', 'Lockheed Martin Corp.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LNT', 'Alliant Energy', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LOW', 'Lowe''s Companies Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LRCX', 'Lam Research Corp.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LULU', 'Lululemon Athletica Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LUV', 'Southwest Airlines Co.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LVS', 'Las Vegas Sands', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LYB', 'LyondellBasell Industries NV', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('LYV', 'Live Nation Entertainment Inc.', 'Communication');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MA', 'Mastercard Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MAA', 'Mid-America Apartment Communities', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MAR', 'Marriott International', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MAS', 'Masco', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MCD', 'McDonald''s Corp.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MCHP', 'Microchip Technology Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MCK', 'McKesson Corporation', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MCO', 'Moody''s Corp.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MDB', 'MongoDB Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MDLZ', 'Mondelez International Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MDT', 'Medtronic', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MET', 'MetLife Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('META', 'Meta Platforms Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MGM', 'MGM Resorts', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MKC', 'McCormick & Co. Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MLM', 'Martin Marietta Materials', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MMC', 'Marsh & McLennan Companies Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MMM', '3M Co.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MNST', 'Monster Beverage', 'Consumer Staples');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MO', 'Altria', 'Consumer Staples');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MOS', 'Mosaic Co.', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MPC', 'Marathon Petroleum Corp.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MPWR', 'Monolithic Power Systems', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MRK', 'Merck & Co. Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MRNA', 'Moderna Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MRO', 'Marathon Oil Corp.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MRSH', 'Marsh McLennan', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MRVL', 'Marvell Technology Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MS', 'Morgan Stanley', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MSCI', 'MSCI Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MSFT', 'Microsoft Corp.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MSI', 'Motorola Solutions', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MTB', 'M&T Bank', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MTD', 'Mettler Toledo', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('MU', 'Micron Technology Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NCLH', 'Norwegian Cruise Line Holdings', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NDAQ', 'Nasdaq Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NDSN', 'Nordson Corporation', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NEE', 'NextEra Energy Inc.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NEM', 'Newmont Corp.', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NET', 'Cloudflare Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NFLX', 'Netflix Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NI', 'NiSource', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NKE', 'Nike Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NOC', 'Northrop Grumman Corp.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NOW', 'ServiceNow Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NRG', 'NRG Energy', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NSC', 'Norfolk Southern Corp.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NTAP', 'NetApp', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NTRS', 'Northern Trust', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NUE', 'Nucor', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NVDA', 'NVIDIA Corp.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NVR', 'NVR, Inc.', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NVS', 'Novartis AG (ADR)', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NWS', 'News Corp (Class B)', 'Communication Services');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NWSA', 'News Corp (Class A)', 'Communication Services');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('NXPI', 'NXP Semiconductors', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('O', 'Realty Income Corp.', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ODFL', 'Old Dominion', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('OKE', 'ONEOK Inc.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('OMC', 'Omnicom Group Inc.', 'Communication');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ON', 'ON Semiconductor Corp.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ORCL', 'Oracle Corp.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ORLY', 'O''Reilly Automotive Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('OTIS', 'Otis Worldwide Corp.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('OXY', 'Occidental Petroleum Corp.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PANW', 'Palo Alto Networks Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PARA', 'Paramount Global', 'Communication');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PAYX', 'Paychex', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PCAR', 'PACCAR Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PCG', 'PG&E Corporation', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PEG', 'Public Service Enterprise Group', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PEP', 'PepsiCo Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PFE', 'Pfizer Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PFG', 'Principal Financial Group', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PG', 'Procter & Gamble Co.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PGR', 'Progressive Corp.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PH', 'Parker-Hannifin Corp.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PHM', 'PulteGroup', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PKG', 'Packaging Corporation of America', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PLD', 'Prologis Inc.', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PLTR', 'Palantir Technologies Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PM', 'Philip Morris International', 'Consumer Staples');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PNC', 'PNC Financial Services Group Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PNR', 'Pentair', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PNW', 'Pinnacle West Capital', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PODD', 'Insulet Corp.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('POOL', 'Pool Corp.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PPG', 'PPG Industries Inc.', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PPL', 'PPL Corporation', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PRU', 'Prudential Financial Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PSA', 'Public Storage', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PSKY', 'Paramount Skydance Corporation', 'Communication Services');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PSX', 'Phillips 66', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PTC', 'PTC Inc.', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PWR', 'Quanta Services Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('PYPL', 'PayPal Holdings Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('Q', 'Qnity Electronics', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('QCOM', 'Qualcomm Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('RCL', 'Royal Caribbean Group', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('REG', 'Regency Centers', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('REGN', 'Regeneron Pharmaceuticals Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('RF', 'Regions Financial Corp.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('RJF', 'Raymond James Financial', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('RL', 'Ralph Lauren Corp.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('RMD', 'ResMed', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ROK', 'Rockwell Automation Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ROL', 'Rollins, Inc.', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ROP', 'Roper Technologies Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ROST', 'Ross Stores Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('RSG', 'Republic Services Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('RTX', 'RTX Corp.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('RVTY', 'Revvity', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SATS', 'EchoStar', 'Communication Services');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SBAC', 'SBA Communications', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SBUX', 'Starbucks Corp.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SCHW', 'Charles Schwab Corp.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SHW', 'Sherwin-Williams Co.', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SIVBQ', 'SVB Financial Group (defunct)', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SJM', 'JM Smucker Co.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SLB', 'Schlumberger NV', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SMCI', 'Super Micro Computer Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SNA', 'Snap-on', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SNDK', 'Sandisk', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SNPS', 'Synopsys Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SNY', 'Sanofi (ADR)', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SO', 'Southern Company', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SOLV', 'Solventum', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SPG', 'Simon Property Group Inc.', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SPGI', 'S&P Global Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SRE', 'Sempra', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('STE', 'Steris', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('STLD', 'Steel Dynamics', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('STT', 'State Street Corporation', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('STX', 'Seagate Technology Holdings PLC', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('STZ', 'Constellation Brands', 'Consumer Staples');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SW', 'Smurfit Westrock', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SWK', 'Stanley Black & Decker Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SWKS', 'Skyworks Solutions Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SYF', 'Synchrony Financial', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SYK', 'Stryker Corp.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('SYY', 'Sysco Corp.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('T', 'AT&T Inc.', 'Communication');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TAP', 'Molson Coors Beverage Company', 'Consumer Staples');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TDG', 'TransDigm Group', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TDY', 'Teledyne Technologies', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TEAM', 'Atlassian Corp.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TECH', 'Bio-Techne', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TEL', 'TE Connectivity PLC', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TER', 'Teradyne Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TFC', 'Truist Financial Corp.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TGT', 'Target Corp.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TJX', 'TJX Companies Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TKO', 'TKO Group Holdings', 'Communication Services');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TMO', 'Thermo Fisher Scientific Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TMUS', 'T-Mobile US Inc.', 'Communication');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TPL', 'Texas Pacific Land Corporation', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TPR', 'Tapestry Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TRGP', 'Targa Resources Corp.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TRMB', 'Trimble Inc.', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TROW', 'T. Rowe Price', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TRV', 'Travelers Companies Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TSCO', 'Tractor Supply Co.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TSLA', 'Tesla Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TSM', 'Taiwan Semiconductor Manufacturing Co. (ADR)', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TSN', 'Tyson Foods', 'Consumer Staples');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TT', 'Trane Technologies', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TTD', 'Trade Desk (The)', 'Communication Services');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TTWO', 'Take-Two Interactive Software Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TXN', 'Texas Instruments Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TXT', 'Textron', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('TYL', 'Tyler Technologies', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('UAL', 'United Airlines Holdings Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('UBER', 'Uber', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('UDR', 'UDR, Inc.', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('UHS', 'Universal Health Services', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ULTA', 'Ulta Beauty Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('UNH', 'UnitedHealth Group Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('UNP', 'Union Pacific Corp.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('UPS', 'United Parcel Service Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('URI', 'United Rentals', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('USB', 'US Bancorp', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('V', 'Visa Inc.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('VEEV', 'Veeva Systems', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('VICI', 'VICI Properties Inc.', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('VLO', 'Valero Energy Corp.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('VLTO', 'Veralto', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('VMC', 'Vulcan Materials Company', 'Materials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('VRSK', 'Verisk Analytics', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('VRSN', 'VeriSign Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('VRT', 'Vertiv', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('VRTX', 'Vertex Pharmaceuticals Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('VST', 'Vistra Corp.', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('VTR', 'Ventas', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('VTRS', 'Viatris', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('VZ', 'Verizon Communications Inc.', 'Communication');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WAB', 'Wabtec', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WAT', 'Waters Corporation', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WBA', 'Walgreens Boots Alliance Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WBD', 'Warner Bros. Discovery Inc.', 'Communication');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WDAY', 'Workday Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WDC', 'Western Digital Corp.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WEC', 'WEC Energy Group', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WELL', 'Welltower Inc.', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WFC', 'Wells Fargo & Co.', 'Finance');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WM', 'Waste Management Inc.', 'Industrial');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WMB', 'Williams Companies Inc.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WMT', 'Walmart Inc.', 'Consumer');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WRB', 'W. R. Berkley Corporation', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WSM', 'Williams-Sonoma, Inc.', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WST', 'West Pharmaceutical Services Inc.', 'Healthcare');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WTW', 'Willis Towers Watson', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WY', 'Weyerhaeuser Co.', 'Real Estate');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('WYNN', 'Wynn Resorts', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('XEL', 'Xcel Energy', 'Utilities');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('XOM', 'Exxon Mobil Corp.', 'Energy');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('XYL', 'Xylem Inc.', 'Industrials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('XYZ', 'Block, Inc.', 'Financials');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('YUM', 'Yum! Brands', 'Consumer Discretionary');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ZBH', 'Zimmer Biomet', 'Health Care');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ZBRA', 'Zebra Technologies', 'Information Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ZS', 'Zscaler Inc.', 'Technology');
INSERT OR REPLACE INTO tickers (symbol, name, sector) VALUES ('ZTS', 'Zoetis Inc.', 'Healthcare');
